---
- name: Configure Ubuntu Laptop
  hosts: localhost
  connection: local
  become: true
  vars:

  pre_tasks:

  - name: Enable extra Ubuntu repos
    shell: apt-add-repository -y -n main universe restricted multiverse
    changed_when: false

  - name: Import helm key
    get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /etc/apt/trusted.gpg.d/helm.asc
      
  - name: Add helm repo
    apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      filename: helm-stable-debian
      update_cache: false

  - name: Add KeePassXC PPA
    apt_repository:
      repo: ppa:phoerious/keepassxc
      filename: keepassxc

  - name: Add Atom gpg key
    get_url:
      url: https://packagecloud.io/AtomEditor/atom/gpgkey
      dest: /etc/apt/trusted.gpg.d/atom.asc

  - name: Add Atom PPA
    apt_repository:
      repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
      filename: atom
      update_cache: false

  - name: Add Multisystem key
    get_url:
      url: http://liveusb.info/multisystem/depot/multisystem.asc
      dest: /etc/apt/trusted.gpg.d/multisystem.asc

  - name: Add multisystem PPA
    apt_repository:
      repo: deb http://liveusb.info/multisystem/depot all main
      filename: multisystem

  #- name: Add Dropbox key
  #  apt_key:
  #    keyserver: pool.sks-keyservers.net
  #    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

  #- name: Add Dropbox repository
  #  apt_repository:
  #    repo: deb https://linux.dropbox.com/ubuntu groovy main
  #    filename: dropbox-official

  - name: Update and upgrade packages
    apt:
      name: "*"
      cache_valid_time: "{{ 60*60*6 }}"
      state: latest

  - name: Install packages
    apt:
      name:
      # prereq
      - apt-transport-https
      - flatpak
      - flatpak-builder
      - lm-sensors
      # Needed for dropbox
      # - python3-gpg
      # cli
      - atop
      - octave
      - btrfs-compsize
      - build-essential
      - curl
      - vim
      - trezor
      - tmux
      - tmuxp
      - zstd
      # gui
      - gimp
      - inkscape
      - keepassxc
      - atom
      - virtualbox
      - multisystem
      - nautilus-dropbox
      - steam
      - gparted
      # Display decorations
      - gnome-tweaks
      - solaar
      - gnome-shell-extensions
      - gnome-shell-extension-system-monitor

  - name: Install snaps
    snap:
      name:
      - spotify
      - multipass
      - canonical-livepatch
      - xmind

  - name: Add flathub remote
    flatpak_remote:
      name: flathub
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
    with_items:
    #- com.axosoft.GitKraken
    - com.calibre_ebook.calibre
    - com.jetbrains.PyCharm-Community
    - net.ankiweb.Anki
    - net.sourceforge.ExtremeTuxRacer
    - org.kde.digikam
    - us.zoom.Zoom
    - com.axosoft.GitKraken 
    - com.slack.Slack
    - com.discordapp.Discord
    #- com.spotify.Client

  - name: Install Shadow.tech
    get_url:
      url: https://update.shadow.tech/launcher/prod/linux/ubuntu_18.04/Shadow.AppImage
      dest: /opt/Shadow.AppImage
      mode: 0755

  #- name: Enable livepatch
  #  shell: canonical-livepatch enable 

  - name: Get current shell extensions
    shell: gnome-extensions list
    register: result
    become: false
    changed_when: false

  - name: Enable gnome shell extensions
    shell: "gnome-extensions enable {{item}}"
    when: item not in result.stdout_lines
    loop:
    - system-monitor@paradoxxx.zero.gmail.com 
    become: false
