---
# Ansible playbook that configures profile settings
- name: Configure user profile
  hosts: localhost
  connection: local
  become: false
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "sudo password?"
  tasks:
    - name: Prereq for dconf module
      apt:
        name: python-psutil
      become: true

    - name: Set gconf settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - key: '/org/gnome/shell/app/switcher/current-workspace-only'
          value: 'true'
        - key: '/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces'
          value: 'true'
