---
- name: Configure workstation
  hosts: localhost
  connection: local
  become: true
  vars:
    packages:
      - imwheel
  tasks:
    - name: Install software
      apt:
        name: "{{packages}}"
