---
# Add and remove packages

- block:

  - name: "Docker ppa: {{ docker_package_state }}"
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
      filename: docker
      state: "{{ docker_package_state }}"
    register: result
  
  - name: "Docker apt packages: {{ docker_package_state }}"
    apt:
      install_recommends: true
      update_cache: "{{ result.changed and docker_package_state == 'present' }}"
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      state: "{{ docker_package_state }}"
    environment:
    - NEEDRESTART_MODE: a

  # Block params
  when: (docker_package_state == 'present') == (docker_install_method == 'apt')

- name: "Docker from snap: {{ docker_package_state }}"
  snap:
    name: docker
    state: "{{ docker_package_state }}"
  when: (docker_package_state == 'present') == (docker_install_method == 'snap')
