---
- name: Configure Ubuntu for work
  hosts: localhost
  connection: local
  become: true
  vars:
    downloads: /tmp

  roles:

  - role: common

  post_tasks:

  - name: Install minikube
    apt:
      deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

- name: Configure user profile
  hosts: localhost
  connection: local
  become: false
  tasks:
  
  #- name: Link standard shell folders
  #  file:
  #    src: "/mnt/c/Users/{{ ansible_env.USER }}/{{ item }}"
  #    dest: "~/{{item}}"
  #    state: link
  #  loop:
  #  - Downloads
  #  - Videos
  #  - Music

  #- name: Link Onedrive shell folders
  #  file:
  #    src: "/mnt/c/Users/{{ ansible_env.USER }}/OneDrive - Nasuni/{{ item }}"
  #    dest: "~/{{item}}"
  #    state: link
  #  loop:
  #  - Documents
  #  - Desktop
  #  - Pictures

  - name: git common settings
    git_config:
      scope: global
      name: "{{ (item|dict2items)[0].key }}"
      value: "{{ (item|dict2items)[0].value }}"
    loop:
    - user.email: snichols@nasuni.com

  #- name: Add me to docker group
  #  user:
  #    name: "{{ ansible_env.USER }}"
  #    groups: docker
  #    append: true
  #  become: true

  #- name: Set minikube driver to docker
  #  command: minikube config set driver docker
  #  changed_when: false

  #- name: Create minikube kubectl alias
  #  lineinfile:
  #    path: ~/.bashrc
  #    regexp: "^alias kubectl="
  #    line: 'alias kubectl="minikube kubectl --"'

  #- name: Add local bin dir to path
  #  lineinfile:
  #    path: ~/.bashrc
  #    line: PATH=.local/bin:$PATH
