---
- name: Configure Ubuntu for work
  hosts: localhost
  connection: local
  become: true
  vars:
    downloads: /tmp

  roles:

  - role: common

  post_tasks:

  - name: Install minikube
    apt:
      deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

  - name: Install theme packages
    apt:
      update_cache: false
      name:
      - yaru-theme-gtk
      - lxappearance

  - name: Install Chromium
    snap:
      name:
      - chromium

- name: Configure user profile
  hosts: localhost
  connection: local
  become: false
  tasks:
  
  #- name: Link standard shell folders
  #  file:
  #    src: "/mnt/c/Users/{{ ansible_env.USER }}/{{ item }}"
  #    dest: "~/{{item}}"
  #    state: link
  #  loop:
  #  - Downloads
  #  - Videos
  #  - Music

  #- name: Link Onedrive shell folders
  #  file:
  #    src: "/mnt/c/Users/{{ ansible_env.USER }}/OneDrive - Nasuni/{{ item }}"
  #    dest: "~/{{item}}"
  #    state: link
  #  loop:
  #  - Documents
  #  - Desktop
  #  - Pictures

  - name: git common settings
    git_config:
      scope: global
      name: "{{ (item|dict2items)[0].key }}"
      value: "{{ (item|dict2items)[0].value }}"
    loop:
    - user.email: snichols@nasuni.com

  - name: Add me to docker group
    user:
      name: "{{ ansible_env.USER }}"
      groups: docker
      append: true
    become: true

  #- name: Set minikube driver to docker
  #  command: minikube config set driver docker
  #  changed_when: false

  #- name: Add local bin dir to path
  #  lineinfile:
  #    path: ~/.bashrc
  #    line: PATH=.local/bin:$PATH

  - name: Create repositories dir
    file:
      path: ~/repositories
      state: directory

  - name: Add github to knwon hosts
    shell: >-
      if [ ! -n "$(grep "^github.com " ~/.ssh/known_hosts)" ]; then
        ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null;
      fi

  - name: Add repos from github
    shell: >-
      curl -s https://api.github.com/users/chinnodog/repos 
      | jq -r ".[].ssh_url" 
      | xargs -P 4 -L1 git clone --recurse-submodules -j8
    args:
      chdir: ~/repositories
      warn: false
    failed_when: false

  - name: Add ZeroBraneStudio repo
    git:
      repo: git@github.com:pkulchenko/ZeroBraneStudio.git
      dest: ~/repositories/ZeroBraneStudio
      update: false

  - name: Install ZeroBraneStudio dependencies
    apt:
      name:
      - libgtk2.0-0
      - xdg-utils
