---
- name: Manage git repositories
  hosts: localhost
  connection: local
  become: false
  module_defaults:
    git:
      update: no
  vars:
    remote_regex: '((git|ssh|http(s)?)|(git@[\w\.]+))(:(//)?)([\w\.@\:\-~]+/)*([\w\.@\:\-~]+).git'
    repos:
      - src: git@github.com:ChinnoDog/chinnodog.github.io.git
      - src: git@github.com:kodekloudhub/certified-kubernetes-administrator-course.git
      - src: https://github.com/bitnami/charts.git
        name: bitnami-charts
      - src: git@github.com:scaleway/scaleway-cli.git
      - src: git@github.com:theforeman/foreman-ansible-modules.git
      - src: git@github.com:dbader/readme-template.git
      - src: git@github.com:openshift/okd.git
      - src: git@github.com:crashvb/docker-sign-verify.git
      - src: git@github.com:ChinnoDog/docker-registry-client-async.git
      - src: git@github.com:crashvb/pytest-gnupg-fixtures.git
      - src: git@gitlab.com:ApprenticeAlf/DeDRM.git
      - src: git@bitbucket.org:ChinnoDog/testlab.git
      - src: git@github.com:scottslowe/learning-tools.git
      - src: git@github.com:ChinnoDog/co1-bap.git
  tasks:

  - name: Fork repo checkouts
    git:
      repo: "{{item.src}}"
      dest: "~/repositories/{{ item.name | default(item.src | regex_search(remote_regex, '\\8') | first) }}"
    loop: "{{repos}}"
    poll: 0
    async: 600
    register: checkout_result
    changed_when: false

  post_tasks:

  - name: Wait for repo checkout completion
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: checkout_jobs
    retries: "{{ (600 / 5) | int }}"
    delay: 5
    until: checkout_jobs.finished
    loop: "{{ checkout_result.results }}"


