---
- name: Manage git repositories
  hosts: localhost
  connection: local
  become: false
  module_defaults:
    git:
      update: no
  vars:
    remote_regex: '((git|ssh|http(s)?)|(git@[\w\.]+))(:(//)?)([\w\.@\:\-~]+/)*([\w\.@\:\-~]+).git'
    repos:
      - src: git@github.com:ChinnoDog/chinnodog.github.io.git
      - src: git@github.com:kodekloudhub/certified-kubernetes-administrator-course.git
      - src: https://github.com/bitnami/charts.git
        name: bitnami-charts
  tasks:

  - name: Check out repos
    git:
      repo: "{{item.src}}"
      dest: "~/repositories/{{ item.name | default(item.src | regex_search(remote_regex, '\\8') | first) }}"
    loop: "{{repos}}"

